<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnhVMWU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnhVMWU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXnhVMWU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXnhVMWU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXnhVMWU\App_KernelDevDebugContainer([
    'container.build_hash' => 'XnhVMWU',
    'container.build_id' => '86adc982',
    'container.build_time' => 1649142495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnhVMWU');
